### ISSUE TITLE
👎

### ISSUE THREAD

**Issue by mr-nv** [GuFFy12/vk-documents-downloader#1]
![image](https://user-images.githubusercontent.com/31269663/132963665-95ee7e64-a3f4-4ba7-8c84-9702d50a3d49.png)

**Comment by GuFFy12** [comment]
![png-transparent-smiley-emoticon-thumb-signal-emoji-dank-face-smiley-thumb-signal](https://user-images.githubusercontent.com/49491499/132977560-1e65a2dd-4634-402a-8771-75d36175e2cb.png)
